### ISSUE TITLE
Why Computation needs an object wrapper?

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_state#21]
The compute function is wrapped by an object, which means extra allocations for each call to e.g. `auto()`. Is there a reason for that?

**Comment by back2dos** [comment]
It's mostly to do with how top down inference works with abstracts.

Without the wrapping, [top type inference tries to infer against the underlying type](https://try.haxe.org/#d8C4b) because [reasons](https://github.com/HaxeFoundation/haxe/issues/3525).

We could resort to [`Dynamic`](https://try.haxe.org/#d03db) or perhaps [`@:coreType`](https://try.haxe.org/#2D36B), but I'm a bit worried if this will really fly on static targets ^^
